# See https://pre-commit.com for more info
# See https://pre-commit.com/hooks.html for more hooks
# See https://www.youtube.com/watch?v=psjz6rwzMdk for how-to on pre-commits

repos:

  # Fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      # File name fixes
      - id: check-case-conflict

      # Generic file fixes
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer

      # File-type specific fixes
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args:
          - "--unsafe"

      # Python-specific fixes
      - id: debug-statements
        language_version: python3

      # Git fixes
      - id: no-commit-to-branch
        args:
          - "--branch=main"

  # Linter
  - repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
      - id: black
        args:
          - "--config=pyproject.toml"
  - repo: https://github.com/asottile/blacken-docs
    rev: "1.13.0"
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - "black>=23.3"

  # Run MyPy type checks
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
      - id: mypy
        files: py_tictoc_timer
        args:
          - "--config-file=pyproject.toml"

  # Reorder Python imports
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        name: isort (python)
        args:
          - "--settings-file=pyproject.toml"
