[tool.poetry]
name = "py-tictoc"
version = "0.1.3"
description = "Time the execution of Python code using syntax similar to MATLAB's tic and toc functions."
authors = ["Chris Mahoney <https://github.com/chrimaho>"]

[tool.poetry.dependencies]
python = ">=3.6,<4"
typeguard = "*"

[tool.poetry.dev-dependencies]
black = "*"
mypy = "*"
pytest = "*"
pytest-clarity = "*"
pytest-cov = "*"
pytest-sugar = "*"
pytest-icdiff = "*"
pytest-xdist = "*"

exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | env
    | venv
)/
'''

[tool.pytest.ini_options]
# https://docs.pytest.org/en/6.2.x/customize.html#pyproject-toml
# Directories that are not visited by pytest collector:
norecursedirs =["hooks", "*.egg", ".eggs", "dist", "build", "docs", ".tox", ".git", "__pycache__"]
doctest_optionflags = ["NUMBER", "NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
