[tool.poetry]
name = "py-tictoc"
version = "0.1.8"
description = "Time the execution of Python code using syntax similar to MATLAB's tic and toc functions."
readme = "README.md"
authors = ["Chris Mahoney <https://github.com/chrimaho>"]
license = "MIT"
repository = "https://github.com/chrimaho/py-tictoc"

[tool.poetry.dependencies]
python = ">=3.6,<4"
typeguard = "~2.13"

[tool.poetry.dev-dependencies]
black = "~22.8"
mypy = "~0.971"
pytest = "~7.1"
pytest-clarity = "~1.0"
pytest-cov = "~3.0"
pytest-sugar = "~0.9"
pytest-icdiff = "~0.6"
pytest-xdist = "~2.5"

[tool.pytest.ini_options]
# https://docs.pytest.org/en/6.2.x/customize.html#pyproject-toml
# Directories that are not visited by pytest collector:
norecursedirs =["hooks", "*.egg", ".eggs", "dist", "build", "docs", ".tox", ".git", "__pycache__"]
doctest_optionflags = ["NUMBER", "NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
